### ISSUE TITLE
Exception during "configure-matrix-authorization-strategy" execution

### ISSUE THREAD

**Issue by antonio-petricca** [samrocketman/jenkins-bootstrap-shared#14]
Hi, I put `configure-matrix-authorization-strategy.groovy` into `/usr/share/jenkins/ref/init.groovy.d/` but during startup I got:

> jenkins.model.Jenkins$5#runTask: GroovyInitScript.init failed perhaps due to plugin dependency issues
> java.lang.ClassFormatError: Illegal class name "jenkins-setup-matrix-authorization$isValidConfig" in class file jenkins-setup-matrix-authorization$isValidConfig
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts.define(ClassLoaderForClassArtifacts.java:44)
> 	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts$1.run(ClassLoaderForClassArtifacts.java:77)
> 	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts$1.run(ClassLoaderForClassArtifacts.java:75)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.codehaus.groovy.reflection.ClassLoaderForClassArtifacts.defineClassAndGetConstructor(ClassLoaderForClassArtifacts.java:75)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteGenerator.compilePogoMethod(CallSiteGenerator.java:222)
> 	at org.codehaus.groovy.reflection.CachedMethod.createPogoMetaMethodSite(CachedMethod.java:233)
> 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.createCachedMethodSite(PogoMetaMethodSite.java:150)
> 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.createPogoMetaMethodSite(PogoMetaMethodSite.java:126)
> 	at groovy.lang.MetaClassImpl.createPogoCallCurrentSite(MetaClassImpl.java:3441)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallCurrentSite(CallSiteArray.java:111)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
> 	at jenkins-setup-matrix-authorization.run(jenkins-setup-matrix-authorization.groovy:184)
> 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
> 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
> 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
> 	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
> 	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
> Caused: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
> Caused: java.lang.Error
> 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
> 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
> 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
> 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1133)
> 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
> 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
> 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

Instead, pasting the code into the Jenkins Console it works as expected.

Could any body point me to the solution?

Thank you so much!

**Edit 1** the issue is related to the _isValidConfig_ method not resolved during execution.

**Comment by antonio-petricca** [comment]
**Solution found** : you must replace into script file name the "-" with "_" in order to get a valid class name at compile time.
